#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wpa_supplicant
Version  : 2.6
Release  : 14
URL      : http://w1.fi/releases/wpa_supplicant-2.6.tar.gz
Source0  : http://w1.fi/releases/wpa_supplicant-2.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: wpa_supplicant-bin
Requires: wpa_supplicant-config
BuildRequires : libnl-dev
BuildRequires : openssl-dev
Patch1: config.patch

%description
wpa_supplicant and hostapd
--------------------------
All Rights Reserved.
These programs are licensed under the BSD license (the one with
advertisement clause removed).

%package bin
Summary: bin components for the wpa_supplicant package.
Group: Binaries
Requires: wpa_supplicant-config

%description bin
bin components for the wpa_supplicant package.


%package config
Summary: config components for the wpa_supplicant package.
Group: Default

%description config
config components for the wpa_supplicant package.


%prep
%setup -q -n wpa_supplicant-2.6
%patch1 -p1

%build
export LANG=C
pushd wpa_supplicant
make V=1  %{?_smp_mflags}
popd

%install
rm -rf %{buildroot}
pushd wpa_supplicant
%make_install
popd
## make_install_append content
chmod -x %{buildroot}/usr/lib/systemd/system/*
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wpa_cli
/usr/bin/wpa_passphrase
/usr/bin/wpa_supplicant

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/wpa_supplicant-nl80211@.service
/usr/lib/systemd/system/wpa_supplicant-wired@.service
/usr/lib/systemd/system/wpa_supplicant.service
/usr/lib/systemd/system/wpa_supplicant@.service
